name: Daily dbt Pipeline Execution

on:
  schedule:
    # 02:15 UTC corresponds to 09:15 AM Vietnam Time (ICT)
    - cron: '15 19 * * *'
  workflow_dispatch: #Manual trigger for the workflow

jobs:
  run_dbt_pipeline:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./

      # Environment variables for Snowflake connection (stored as GitHub Secrets)
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd AI_dbt_transformation_and_create_dim_fact

      - name: Install dbt Packages
        run: dbt deps

      - name: Run dbt Source Freshness Check
        run: dbt source freshness

      - name: Execute dbt Build (Run Models & Data Tests)
        run: dbt build